version: '2'
services:
    testaudit-app:
        image: testaudit
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://testaudit-postgresql:5432/testaudit
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://testaudit-elasticsearch:9200
        ports:
            - 8080:8080
    testaudit-postgresql:
        extends:
            file: postgresql.yml
            service: testaudit-postgresql
    testaudit-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: testaudit-elasticsearch
