version: '2'
services:
    testaudit-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/testaudit/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=testaudit
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
